services:
  # postgres:
  #   image: postgres
  #   environment:
  #     POSTGRES_PASSWORD: "Postgres2022!"
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  nats:
    image: nats:latest
    env_file:
      - .env
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["--auth", "${NATS_AUTH_TOKEN}"]

#  zookeeper:
#    image: wurstmeister/zookeeper
#    ports:
#      - "2181:2181"
#    environment:
#      ZOOKEEPER_SASL_ENABLED: "true"
#      ZOOKEEPER_OPTS: "-Djava.security.auth.login.config=/etc/zookeeper/zookeeper_jaas.conf"
#      ZOOKEEPER_AUTH_PROVIDER_1: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
#    volumes:
#      - ./zookeeper_jaas.conf:/etc/zookeeper/zookeeper_jaas.conf
#
#  kafka-unsecured:
#    image: wurstmeister/kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: localhost
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    depends_on:
#      - zookeeper
#
#  kafka-secured:
#    image: wurstmeister/kafka
#    ports:
#      - "9093:9093"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: localhost
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LISTENERS: SASL_PLAINTEXT://:9093
#      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://localhost:9093
#      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
#      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
#      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
#      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
#      KAFKA_ZOOKEEPER_SET_ACL: "true"
#      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 60000
#    volumes:
#      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
#    depends_on:
#      - zookeeper

# volumes:
#   postgres_data:
