services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["--auth", "a428978a-7bce-4bcb-a082-a760643edd00"]

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  pubsub-emulator:
    image: google/cloud-sdk:latest # You can use the official gcloud SDK image
    command: gcloud beta emulators pubsub start --project=dev-local --host-port=0.0.0.0:8085
    ports:
      - "8085:8085" # Map the emulator port to your host
    environment:
      # Optional: Set environment variables for your application to connect to the emulator
      PUBSUB_EMULATOR_HOST: "pubsub-emulator:8085"
      PUBSUB_PROJECT_ID: "dev-local"
volumes:
  rabbitmq_data:
