// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package icons

import (
	"fmt"

	"fyne.io/fyne/v2"
)

// ThemeToggleIcon returns the appropriate theme toggle icon based on current theme
func ThemeToggleIcon(isDark bool) fyne.Resource {
	var iconPath string
	if isDark {
		iconPath = "icons/png/light-mode.png" // Show light mode icon when in dark theme
	} else {
		iconPath = "icons/png/dark-mode.png" // Show dark mode icon when in light theme
	}

	resource, err := fyne.LoadResourceFromPath(iconPath)
	if err != nil {
		fmt.Printf("Error loading theme toggle icon: %v\n", err)
		return nil
	}
	return resource
}

// AddServerIcon returns the add server icon
func AddServerIcon() fyne.Resource {
	resource, err := fyne.LoadResourceFromPath("icons/png/add-server.png")
	if err != nil {
		fmt.Printf("Error loading add server icon: %v\n", err)
		return nil
	}
	return resource
}

// ExitIcon returns the exit icon
func ExitIcon() fyne.Resource {
	resource, err := fyne.LoadResourceFromPath("icons/png/exit.png")
	if err != nil {
		fmt.Printf("Error loading exit icon: %v\n", err)
		return nil
	}
	return resource
}

// PublisherIcon returns the publisher icon
func PublisherIcon() fyne.Resource {
	resource, err := fyne.LoadResourceFromPath("icons/png/publisher.png")
	if err != nil {
		fmt.Printf("Error loading publisher icon: %v\n", err)
		return nil
	}
	return resource
}

// SubscriberIcon returns the subscriber icon
func SubscriberIcon() fyne.Resource {
	resource, err := fyne.LoadResourceFromPath("icons/png/subscriber.png")
	if err != nil {
		fmt.Printf("Error loading subscriber icon: %v\n", err)
		return nil
	}
	return resource
}
