// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package icons

import (
	"fmt"

	"fyne.io/fyne/v2"
)

func ThemeToggleIcon() fyne.Resource {
	// This function returns a fyne.Resource for the theme toggle icon.
	resource, err := fyne.LoadResourceFromPath("icons/png/dark-mode.png")
	if err != nil {
		fmt.Printf("Error loading theme toggle icon: %v\n", err)
		return nil
	}
	return resource
}
