name: Build and Compress Binaries with fyne-cross

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install fyne-cross
      run: |
        go install github.com/fyne-io/fyne-cross@latest

    - name: Build All Binaries
      run: |
        make all

    - name: Compress and Rename Files
      run: |
        mkdir -p build/compressed
        for platform in windows linux darwin; do
          for arch in amd64 arm64; do
            case $platform in
              windows)
                find fyne-cross/dist -name "*${platform}-${arch}*.exe.zip" -exec cp {} build/compressed/${platform}-${arch}.zip \;
                ;;
              linux|darwin)
                find fyne-cross/dist -name "*${platform}-${arch}*.tar.xz" -exec cp {} build/compressed/${platform}-${arch}.tar.xz \;
                ;;
            esac
          done
        done

    - name: Upload Compressed Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: "compressed-binaries"
        path: build/compressed/*
