name: Build and Compress Binaries

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build Binary
      run: |
        make clean
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} make build

    - name: Compress Binary
      run: |
        mkdir -p build/compressed
        cd build/${{ matrix.os }}/${{ matrix.arch }}
        if [ "${{ matrix.os }}" == "windows" ]; then
          zip ../../compressed/${{ matrix.os }}-${{ matrix.arch }}.zip nats-client.exe
        else
          tar -czf ../../compressed/${{ matrix.os }}-${{ matrix.arch }}.tar.gz nats-client
        fi

    - name: Upload Compressed Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}-binary
        path: build/compressed/${{ matrix.os }}-${{ matrix.arch }}.*
