name: Build Binaries for Linux, Windows, and macOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64] # Adicionado suporte para arm64

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build Binary
      run: |
        make clean
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} make build

    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}-binary
        path: build/${{ matrix.os }}/${{ matrix.arch }}/nats-client
