name: Build and Compress Binaries with fyne-cross

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install fyne-cross
      run: |
        go install github.com/fyne-io/fyne-cross@latest

    - name: Build Binary with fyne-cross
      run: |
        fyne-cross ${{ matrix.os }} -arch=${{ matrix.arch }} -output build/${{ matrix.os }}-${{ matrix.arch }}

    - name: Compress Binary
      run: |
        mkdir -p build/compressed
        cd build
        if [ "${{ matrix.os }}" == "windows" ]; then
          zip compressed/${{ matrix.os }}-${{ matrix.arch }}.zip ${{ matrix.os }}-${{ matrix.arch }}/*.exe
        else
          tar -czf compressed/${{ matrix.os }}-${{ matrix.arch }}.tar.gz ${{ matrix.os }}-${{ matrix.arch }}/*
        fi

    - name: Upload Compressed Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}-binary
        path: build/compressed/${{ matrix.os }}-${{ matrix.arch }}.*
